name: Dev Deployment
concurrency: promotion
on:
  push:
    branches: main

jobs:
  deploy-bundle:
    name: "Deploy bundle"
    runs-on: ubuntu-latest
    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
      DATABRICKS_BUNDLE_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy
      - run: databricks bundle run ddl
