name: Prod Deployment
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Commit SHA to deploy (defaults to latest on main)'
        required: false
concurrency:
  group: prod-deploy
  cancel-in-progress: false
jobs:

  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
      DATABRICKS_BUNDLE_ENV: prod

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.sha || 'main' }}
      - uses: databricks/setup-cli@v1
      - run: databricks bundle validate
      - run: databricks bundle deploy
