name: CI
on:
  pull_request:
jobs:

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements/lint.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/lint.txt
        working-directory: .

      - name: Run linting checks
        run: bash ./lint.sh

  validate-bundle:
    name: "Validate bundle"
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: databricks/setup-cli@main
      - run: databricks bundle validate   
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
