name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: main

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - id: deployment
      uses: sphinx-notes/pages@v3