name: Databricks Asset Bundle CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:          # allow a manual rerun if needed

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST:  ${{ secrets.DATABRICKS_HOST_DEV }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}
      DATABRICKS_BUNDLE_ENV: dev
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle validate
      - run: databricks bundle deploy
      - run: databricks bundle run test --refresh-all --watch   # integration test

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    **environment: prod**        # ←‑‑ this line makes the job wait
    env:
      DATABRICKS_HOST:  ${{ secrets.DATABRICKS_HOST_PROD }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_PROD }}
      DATABRICKS_BUNDLE_ENV: prod
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle validate
      - run: databricks bundle deploy
