name: Databricks Asset Bundle CI/CD

# Ensure that only a single job or workflow using the same concurrency group
# runs at a time.
concurrency: 1

# Trigger this workflow whenever a pull request is opened against the repo's
# main branch or an existing pull request's head branch is updated.
on:
  pull_request:          # fast CI for feature branches
  push:
    branches: main

concurrency: promotion

jobs:
  deploy-dev:
    name: 'Deploy bundle'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
          DATABRICKS_BUNDLE_ENV: dev


  # deploy-prod:
  #   needs: deploy-dev
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: databricks/setup-cli@main
  #     - run: databricks bundle validate
  #     - run: databricks bundle deploy

  #   environment: prod
  #   env:
  #     DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_PAT }}
  #     DATABRICKS_BUNDLE_ENV: prod
