name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: main

  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install documentation dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/autodoc.txt

      - name: Build documentation
        run: sphinx-build -b html docs docs/_build/html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build